"use client";

import { useState, useCallback, useEffect, useRef, useSyncExternalStore } from "react";
import { useTheme } from "next-themes";
import {
  Search, Wand2, Download, TrendingUp, Info, Copy, Check,
  Moon, Sun, Share2, Trash2, Eye, Clock, Tag, Hash,
  ChevronDown, ChevronUp, ExternalLink, Sparkles, BarChart3,
  Users, Zap, ArrowUp, Volume2, ImageIcon, Crown, Shield,
  X, Star, Upload, RefreshCw, Lock, Phone, CreditCard, MessageCircle,
  FileText, Heart, Play
} from "lucide-react";

interface VideoDetail {
  videoId: string; title: string; description: string;
  tags: string[]; hashtags: string; category: string;
  duration: string; uploadDate: string; daysAgo: string;
  channelName: string; viewCount: string; thumbnailUrl: string;
}
interface SEOData { title: string; description: string; tags: string[]; hashtags: string[]; }
interface TrendVideo {
  videoId: string; title: string; channelName: string;
  thumbnailUrl: string; viewCount: string; duration: string; published: string;
}
interface TranscriptData { videoId: string; title?: string; channel?: string; transcript: string; language: string; source: string; isAutoGenerated: boolean; }
interface AdPlatform {
  id: string; name: string; clientId: string; slotId: string;
  enabled: boolean; scriptUrl: string; adType?: string;
}
interface AdminSettings {
  freeLimit: number; proPrice: number; enterprisePrice: number;
  faceSwapEnabled: boolean; characterReplaceEnabled: boolean;
  jazzcashNumber: string; jazzcashName: string; paymentEnabled: boolean;
  maintenanceMode: boolean; adPlatforms: AdPlatform[];
}

const THUMB_STYLES = [
  {id:"gaming",label:"Gaming",color:"bg-purple-500/20 text-purple-400 border-purple-500/30"},
  {id:"vlog",label:"Vlog",color:"bg-pink-500/20 text-pink-400 border-pink-500/30"},
  {id:"tutorial",label:"Tutorial",color:"bg-blue-500/20 text-blue-400 border-blue-500/30"},
  {id:"news",label:"News",color:"bg-red-500/20 text-red-400 border-red-500/30"},
  {id:"reaction",label:"Reaction",color:"bg-yellow-500/20 text-yellow-400 border-yellow-500/30"},
  {id:"music",label:"Music",color:"bg-green-500/20 text-green-400 border-green-500/30"},
  {id:"tech",label:"Tech",color:"bg-cyan-500/20 text-cyan-400 border-cyan-500/30"},
  {id:"cooking",label:"Cooking",color:"bg-orange-500/20 text-orange-400 border-orange-500/30"},
];

const DEFAULT_SETTINGS: AdminSettings = {
  freeLimit: 5, proPrice: 0, enterprisePrice: 0,
  faceSwapEnabled: false, characterReplaceEnabled: false,
  jazzcashNumber: "03225415760", jazzcashName: "JazzCash",
  maintenanceMode: false, paymentEnabled: true, adPlatforms: [],
};

function Confetti() {
  const [particles] = useState(() => Array.from({length:40}, (_,i) => ({
    id:i, x:Math.random()*100, y:Math.random()*100,
    c:["#FF6B6B","#4ECDC4","#45B7D1","#96CEB4","#FFEAA7","#DDA0DD","#98D8C8","#F7DC6F","#BB8FCE","#85C1E9"][i%10],
    r:Math.random()*360
  })));
  return (<div className="fixed inset-0 pointer-events-none z-[100] overflow-hidden">{particles.map(p => (
    <div key={p.id} className="absolute animate-bounce" style={{
      left:`${p.x}%`,top:`${p.y}%`,width:"8px",height:"8px",
      backgroundColor:p.c, borderRadius:Math.random()>0.5?"50%":"2px",
      transform:`rotate(${p.r}deg)`, opacity:0.8, animationDuration:`${1+Math.random()*2}s`
    }}/>
  ))}</div>);
}

function CopyBtn({ text, label }: { text: string; label: string }) {
  const [ok, setOk] = useState(false);
  const copy = () => { navigator.clipboard.writeText(text); setOk(true); setTimeout(()=>setOk(false),2000); };
  return (<button onClick={copy} className="flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-medium transition-all bg-primary/10 hover:bg-primary/20 text-primary">
    {ok ? <><Check size={12}/> Copied!</> : <><Copy size={12}/> {label}</>}
  </button>);
}

function CopyableHashtag({ text }: { text: string }) {
  const [ok, setOk] = useState(false);
  const copy = (e: React.MouseEvent) => { e.stopPropagation(); navigator.clipboard.writeText(text); setOk(true); setTimeout(()=>setOk(false),1500); };
  return (<span onClick={copy} className="px-2.5 py-1 rounded-lg bg-orange-500/10 text-orange-400 text-xs font-medium cursor-pointer hover:bg-orange-500/20 transition-colors">
    {ok ? <span className="flex items-center gap-1"><Check size={11}/> Copied</span> : text}
  </span>);
}

function useLiveCounter() {
  const base = useRef(128547 + Math.floor(Math.random()*500));
  const [c, setC] = useState(base.current);
  return useSyncExternalStore(
    (cb) => { const iv = setInterval(()=>setC(p=>p+Math.floor(Math.random()*3)+1), 8000); return ()=>clearInterval(iv); },
    () => c, () => 128547
  );
}

function useMounted() {
  const [mounted, setMounted] = useState(false);
  const r = useRef(false);
  useEffect(() => { if (r.current) return; r.current = true; requestAnimationFrame(() => setMounted(true)); }, []);
  return mounted;
}

function AdBanner({ platform, position }: { platform: AdPlatform; position: string }) {
  if (!platform.enabled || !platform.clientId) return null;
  const adType = platform.adType || "banner";
  const pid = platform.clientId;
  const slot = platform.slotId || "";

  if (platform.id === "google-adsense") {
    return (
      <div className="my-4 rounded-xl border border-border/50 bg-muted/20 p-1 text-center overflow-hidden">
        <div className="text-[9px] text-muted-foreground/50 mb-1">Advertisement</div>
        <ins className="adsbygoogle"
          style={{ display: "block", minHeight: position === "top" ? "100px" : "90px" }}
          data-ad-client={pid}
          data-ad-slot={slot}
          data-ad-format="auto"
          data-full-width-responsive="true"/>
      </div>
    );
  }

  if (platform.id === "propellerads" && slot) {
    return (
      <div className="my-4 rounded-xl border border-border/50 bg-muted/20 p-1 text-center overflow-hidden">
        <div className="text-[9px] text-muted-foreground/50 mb-1">Advertisement - PropellerAds</div>
        <div id={slot} className="min-h-[90px]">
          <div className="py-6 text-center text-[10px] text-muted-foreground">PropellerAds Zone: {slot}</div>
        </div>
      </div>
    );
  }

  if (platform.id === "adsterra" && slot) {
    return (
      <div className="my-4 rounded-xl border border-border/50 bg-muted/20 p-1 text-center overflow-hidden">
        <div className="text-[9px] text-muted-foreground/50 mb-1">Advertisement - Adsterra</div>
        <div id={slot} className="min-h-[90px]">
          <div className="py-6 text-center text-[10px] text-muted-foreground">Adsterra Placement: {slot}</div>
        </div>
      </div>
    );
  }

  if (platform.id === "monetag" && slot) {
    return (
      <div className="my-4 rounded-xl border border-border/50 bg-muted/20 p-1 text-center overflow-hidden">
        <div className="text-[9px] text-muted-foreground/50 mb-1">Advertisement - Monetag</div>
        <div id={`mtag_${slot}`} className="min-h-[90px]">
          <div className="py-6 text-center text-[10px] text-muted-foreground">Monetag Widget: {slot}</div>
        </div>
      </div>
    );
  }

  if (platform.id === "media-net") {
    return (
      <div className="my-4 rounded-xl border border-border/50 bg-muted/20 p-1 text-center overflow-hidden">
        <div className="text-[9px] text-muted-foreground/50 mb-1">Advertisement - Media.net</div>
        <div id={`M${slot || pid.replace(/[^a-zA-Z0-9]/g,'')}`} className="min-h-[90px]">
          <div className="py-6 text-center text-[10px] text-muted-foreground">Media.net Ad - CID: {pid}</div>
        </div>
      </div>
    );
  }

  if (platform.id === "taboola" && pid) {
    return (
      <div className="my-4 rounded-xl border border-border/50 bg-muted/20 overflow-hidden">
        <div className="text-[9px] text-muted-foreground/50 px-2 pt-1">Sponsored - Taboola</div>
        <div id={`taboola-below-article-thumbnails-${position}`} className="py-4 px-2">
          <div className="py-4 text-center text-[10px] text-muted-foreground">Taboola - Publisher: {pid}</div>
        </div>
      </div>
    );
  }

  return (
    <div className="my-4 rounded-xl border border-border/50 bg-muted/20 p-1 text-center overflow-hidden">
      <div className="text-[9px] text-muted-foreground/50 mb-1">Advertisement</div>
      <div className="py-6 text-center">
        <div className="text-[10px] text-muted-foreground">{platform.name}</div>
        {pid && <div className="text-[9px] text-muted-foreground/50 mt-1">ID: {pid}</div>}
        {slot && <div className="text-[9px] text-muted-foreground/50">Slot: {slot}</div>}
      </div>
    </div>
  );
}

export default function Home() {
  const mounted = useMounted();
  const { theme, setTheme } = useTheme();
  const [tab, setTab] = useState<"seo"|"thumb"|"detail"|"trend"|"thumbgen"|"transcript">("seo");
  const [loading, setLoading] = useState(false);
  const [showConfetti, setShowConfetti] = useState(false);
  const counter = useLiveCounter();
  const [history, setHistory] = useState<string[]>(() => {
    if (typeof window === "undefined") return [];
    try { const h = localStorage.getItem("yt-history"); return h ? JSON.parse(h) : []; } catch { return []; }
  });
  const [seoResult, setSeoResult] = useState<SEOData|null>(null);
  const [detailResult, setDetailResult] = useState<VideoDetail|null>(null);
  const [thumbUrl, setThumbUrl] = useState("");
  const [thumbId, setThumbId] = useState("");
  const [expandDesc, setExpandDesc] = useState(false);
  const [showPlans, setShowPlans] = useState(false);
  const [showPayment, setShowPayment] = useState(false);
  const [payPlan, setPayPlan] = useState<"pro"|"enterprise">("pro");
  const [adminSettings, setAdminSettings] = useState<AdminSettings>(DEFAULT_SETTINGS);

  const [seoTopic, setSeoTopic] = useState("");
  const [thumbInput, setThumbInput] = useState("");
  const [detailInput, setDetailInput] = useState("");
  const [transcriptInput, setTranscriptInput] = useState("");
  const [transcriptResult, setTranscriptResult] = useState<TranscriptData|null>(null);
  const [copied, setCopied] = useState(false);
  const [seoExpandDesc, setSeoExpandDesc] = useState(false);

  const adminLoadedRef = useRef(false);
  useEffect(() => {
    if (adminLoadedRef.current) return; adminLoadedRef.current = true;
    queueMicrotask(async () => {
      try {
        const r = await fetch("/api/admin-settings");
        if (r.ok) { const d = await r.json(); if (d.settings) setAdminSettings(d.settings); }
      } catch {}
    });
  }, []);

  const saveHistory = useCallback((item:string) => {
    setHistory(prev => { const n=[item,...prev.filter(x=>x!==item)].slice(0,20); localStorage.setItem("yt-history",JSON.stringify(n)); return n; });
  }, []);

  const fireConfetti = () => { setShowConfetti(true); setTimeout(()=>setShowConfetti(false),4000); };

  const extractId = (u:string) => {
    const m = u.match(/(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/|youtube\.com\/shorts\/)([a-zA-Z0-9_-]{11})/);
    return m ? m[1] : (u.length===11 && /^[a-zA-Z0-9_-]+$/.test(u) ? u : null);
  };

  const handleSEO = async () => {
    if(!seoTopic.trim()) return; setLoading(true); fireConfetti();
    try { const r = await fetch("/api/seo-generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic:seoTopic})}); const d = await r.json(); if(d.error) alert(d.error); else { setSeoResult(d); saveHistory(`SEO: ${seoTopic}`); } } catch(e:any) { alert("Error: "+e.message); }
    setLoading(false);
  };

  const handleThumb = () => {
    const id = extractId(thumbInput);
    if(!id) { alert("Invalid YouTube URL"); return; }
    setThumbId(id); setThumbUrl(`https://img.youtube.com/vi/${id}/maxresdefault.jpg`); saveHistory(`Thumb: ${id}`); fireConfetti();
  };

  const handleDetail = async (overrideUrl?: string) => {
    const inputUrl = overrideUrl || detailInput;
    const id = extractId(inputUrl);
    if(!id) { alert("Invalid YouTube URL"); return; } setLoading(true);
    try { const r = await fetch("/api/video-detail",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:inputUrl})}); const d = await r.json(); if(d.error) alert(d.error); else { setDetailResult(d); saveHistory(`Detail: ${id}`); fireConfetti(); } } catch(e:any) { alert("Error: "+e.message); }
    setLoading(false);
  };

  const handleShare = () => {
    const url = window.location.href;
    if (navigator.clipboard) {
      navigator.clipboard.writeText(url).then(() => {
        const btn = document.activeElement as HTMLElement;
        if (btn) { const orig = btn.innerHTML; btn.innerHTML = '<span style="font-size:11px">Copied!</span>'; setTimeout(() => { btn.innerHTML = orig; }, 2000); }
      }).catch(() => {});
    }
  };

  const handleTranscript = async () => {
    if(!transcriptInput.trim()) return;
    setLoading(true); setTranscriptResult(null);
    try {
      const r = await fetch("/api/transcript",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:transcriptInput})});
      const d = await r.json();
      if(d.error) alert(d.error);
      else { setTranscriptResult(d); saveHistory(`Transcript: ${transcriptInput}`); }
    } catch(e:any) { alert("Error: "+e.message); }
    setLoading(false);
  };

  const copyTranscript = () => {
    if(transcriptResult?.transcript) {
      navigator.clipboard.writeText(transcriptResult.transcript);
      setCopied(true);
      setTimeout(()=>setCopied(false),2000);
    }
  };

  const openPayment = (plan: "pro"|"enterprise") => { setPayPlan(plan); setShowPayment(true); };

  const tabs = [
    {id:"seo" as const,icon:Wand2,label:"AI SEO"},
    {id:"thumb" as const,icon:Download,label:"Thumb DL"},
    {id:"detail" as const,icon:Info,label:"Video Detail"},
    {id:"trend" as const,icon:TrendingUp,label:"Trending"},
    {id:"transcript" as const,icon:FileText,label:"Transcript"},
    {id:"thumbgen" as const,icon:ImageIcon,label:"AI Thumb Gen"},
  ];

  if(!mounted) return (
    <div style={{minHeight:"100vh",background:"#09090b",display:"flex",alignItems:"center",justifyContent:"center",flexDirection:"column",gap:"12px"}}>
      <div style={{width:"40px",height:"40px",border:"4px solid #dc2626",borderTopColor:"transparent",borderRadius:"50%",animation:"spin 1s linear infinite"}}/>
      <div style={{color:"#ffffff",fontSize:"14px",fontWeight:"600"}}>Loading...</div>
      <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
    </div>
  );

  const planPrice = payPlan === "pro" ? adminSettings.proPrice : adminSettings.enterprisePrice;
  const planName = payPlan === "pro" ? "Pro" : "Enterprise";

  return (
    <div className="min-h-screen bg-background text-foreground transition-colors duration-300">
      {showConfetti && <Confetti/>}

      {adminSettings.adPlatforms.filter(p => p.enabled && p.clientId).map(p => {
        let src = p.scriptUrl;
        if (src) src = src.replace("{CLIENT_ID}", p.clientId);
        if (!src) return null;
        if (p.id === "google-adsense") src = `https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${p.clientId}`;
        return <script key={p.id} async src={src} crossOrigin="anonymous"/>;
      })}

      <header className="sticky top-0 z-50 backdrop-blur-xl bg-background/80 border-b border-border">
        <div className="max-w-4xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-red-500 to-red-700 flex items-center justify-center"><Sparkles size={18} className="text-white"/></div>
            <div>
              <h1 className="text-base font-bold bg-gradient-to-r from-red-500 to-orange-500 bg-clip-text text-transparent">YT SEO Toolkit</h1>
              <p className="text-[10px] text-muted-foreground -mt-0.5">AI-Powered YouTube Tools</p>
            </div>
          </div>
          <div className="flex items-center gap-1.5">
            <button onClick={()=>setShowPlans(true)} className="p-2 rounded-lg hover:bg-accent transition-colors" title="Plans"><Crown size={18} className="text-yellow-500"/></button>
            <button onClick={handleShare} className="p-2 rounded-lg hover:bg-accent transition-colors" title="Share"><Share2 size={18}/></button>
            <button onClick={()=>setTheme(theme==="dark"?"light":"dark")} className="p-2 rounded-lg hover:bg-accent transition-colors" title="Theme">{theme==="dark"?<Sun size={18}/>:<Moon size={18}/>}</button>
          </div>
        </div>
      </header>

      <div className="bg-gradient-to-r from-red-600 via-red-500 to-orange-500 text-white text-center py-1.5 px-4">
        <div className="flex items-center justify-center gap-2 text-xs font-semibold animate-pulse"><Zap size={14}/><span>{counter.toLocaleString()} people used today</span><Eye size={14}/></div>
      </div>

      {adminSettings.adPlatforms.filter(p=>p.enabled).map(p => <AdBanner key={p.id} platform={p} position="top"/>)}

      <div className="sticky top-[57px] z-40 backdrop-blur-xl bg-background/80 border-b border-border overflow-x-auto">
        <div className="max-w-4xl mx-auto flex">{tabs.map(t=>(
          <button key={t.id} onClick={()=>setTab(t.id)} className={`flex items-center gap-1.5 px-3.5 py-3 text-xs font-medium whitespace-nowrap border-b-2 transition-all ${tab===t.id?"border-red-500 text-red-500":"border-transparent text-muted-foreground hover:text-foreground"}`}>
            <t.icon size={15}/>{t.label}
          </button>
        ))}</div>
      </div>

      <main className="max-w-4xl mx-auto px-4 py-6 pb-24">

        {tab==="seo" && (
          <div className="space-y-5 animate-in fade-in duration-300">
            <div className="bg-card rounded-2xl border border-border p-5 shadow-sm">
              <div className="flex items-center gap-2 mb-3"><Wand2 size={20} className="text-red-500"/><h2 className="text-lg font-bold">AI SEO Generator</h2></div>
              <p className="text-sm text-muted-foreground mb-4">Enter your video topic and get optimized title, description &amp; hashtags!</p>
              <input value={seoTopic} onChange={e=>setSeoTopic(e.target.value)} onKeyDown={e=>e.key==="Enter"&&handleSEO()} placeholder="e.g. How to make biryani at home" className="w-full px-4 py-3 rounded-xl bg-background border border-border text-sm focus:outline-none focus:ring-2 focus:ring-red-500/50 placeholder:text-muted-foreground/50 mb-3"/>
              <button onClick={handleSEO} disabled={loading||!seoTopic.trim()} className="w-full py-3 rounded-xl bg-gradient-to-r from-red-500 to-red-600 text-white font-medium text-sm hover:from-red-600 hover:to-red-700 transition-all disabled:opacity-50 flex items-center justify-center gap-1.5">
                {loading?<span className="animate-pulse">Generating...</span>:<><Sparkles size={15}/> Generate</>}
              </button>
            </div>
            {seoResult && (
              <div className="space-y-3 animate-in fade-in slide-in-from-bottom-4 duration-500">
                <div className="bg-card rounded-2xl border border-border p-4 shadow-sm"><div className="flex items-center justify-between mb-2"><div className="flex items-center gap-1.5 text-sm font-semibold"><ArrowUp size={15} className="text-blue-500"/>Title</div><CopyBtn text={seoResult.title} label="Copy"/></div><p className="text-sm text-foreground/90">{seoResult.title}</p></div>
                <div className="bg-card rounded-2xl border border-border p-4 shadow-sm">
                  <div className="flex items-center justify-between mb-2"><div className="flex items-center gap-1.5 text-sm font-semibold"><Volume2 size={15} className="text-green-500"/>Description</div><CopyBtn text={seoResult.description} label="Copy"/></div>
                  <p className={`text-sm text-foreground/90 whitespace-pre-line ${!seoExpandDesc && seoResult.description.length>300?"line-clamp-4":""}`
