import { NextRequest, NextResponse } from "next/server";
import ZAI from "z-ai-web-dev-sdk";

export const maxDuration = 30;

export async function POST(req: NextRequest) {
  try {
    const { url } = await req.json();
    if (!url) return NextResponse.json({ error: "URL required" }, { status: 400 });

    const m = url.match(/(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/|youtube\.com\/shorts\/)([a-zA-Z0-9_-]{11})/);
    const videoId = m ? m[1] : (url.length === 11 && /^[a-zA-Z0-9_-]+$/.test(url) ? url : null);
    if (!videoId) return NextResponse.json({ error: "Invalid YouTube URL" }, { status: 400 });

    let title = "";
    let channel = "";
    try {
      const nr = await fetch(`https://noembed.com/embed?url=https://www.youtube.com/watch?v=${videoId}`, { signal: AbortSignal.timeout(5000) });
      if (nr.ok) { const nd = await nr.json(); title = nd.title || ""; channel = nd.author_name || ""; }
    } catch {}

    try {
      const innertubeBody = {
        context: { client: { clientName: "WEB", clientVersion: "2.20240415.00.00", hl: "en", gl: "US" } },
        videoId: videoId,
      };
      const res = await fetch("https://www.youtube.com/youtubei/v1/player?prettyPrint=false", {
        method: "POST",
        headers: { "Content-Type": "application/json", "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" },
        body: JSON.stringify(innertubeBody),
        signal: AbortSignal.timeout(8000),
      });
      if (res.ok) {
        const data = await res.json();
        const captions = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
        if (captions && captions.length > 0) {
          let track = captions.find((c: any) => c.languageCode === "en") || captions[0];
          const baseUrl = track?.baseUrl;
          if (baseUrl) {
            try {
              const capRes = await fetch(baseUrl + "&fmt=json3", { signal: AbortSignal.timeout(8000) });
              if (capRes.ok) {
                const capData = await capRes.json();
                const events = capData?.events;
                if (events && events.length > 0) {
                  const textParts: string[] = [];
                  for (const ev of events) {
                    if (ev.segs) {
                      const lineText = ev.segs.map((s: any) => s.utf8 || "").join("");
                      if (lineText.trim()) textParts.push(lineText.trim());
                    }
                  }
                  const transcript = textParts.join(" ").trim();
                  if (transcript.length > 50) {
                    return NextResponse.json({ videoId, title: title || undefined, channel: channel || undefined, transcript, language: track.languageCode || "unknown", source: "youtube", isAutoGenerated: (track.kind || "").includes("asr") });
                  }
                }
              }
            } catch {}
            try {
              const vttRes = await fetch(baseUrl, { signal: AbortSignal.timeout(8000) });
              if (vttRes.ok) {
                const vtt = await vttRes.text();
                const lines = vtt.split("\n");
                const textLines: string[] = [];
                for (const line of lines) {
                  const cleaned = line.replace(/<[^>]+>/g, "").trim();
                  if (cleaned && !cleaned.includes("-->") && cleaned !== "WEBVTT" && !cleaned.startsWith("Kind:") && !cleaned.startsWith("Language:")) {
                    textLines.push(cleaned);
                  }
                }
                const transcript = textLines.join(" ").trim();
                if (transcript.length > 50) {
                  return NextResponse.json({ videoId, title: title || undefined, channel: channel || undefined, transcript, language: track.languageCode || "unknown", source: "youtube", isAutoGenerated: (track.kind || "").includes("asr") });
                }
              }
            } catch {}
          }
        }
      }
    } catch {}

    const instances = ["inv.nadeko.net","invidious.fdn.fr","vid.puffyan.us","invidious.nerdvpn.de","yewtu.be","invidious.jing.rocks","invidious.privacyredirect.com","invidious.protokoll.zone","yt.artworks.thebackupbox.net","invidious.perennialte.ch"];
    for (const host of instances) {
      try {
        const res = await fetch(`https://${host}/api/v1/captions/${videoId}`, { signal: AbortSignal.timeout(5000) });
        if (!res.ok) continue;
        const data = await res.json();
        if (data.captions?.length > 0) {
          const getLang = (c: any) => c.language_code || c.languageCode || "";
          const getLabel = (c: any) => c.label || c.name || "";
          let cap = data.captions.find((c: any) => getLang(c) === "en" || getLabel(c).toLowerCase().includes("english")) || data.captions[0];
          if (cap) {
            const capUrl = cap.url?.startsWith("http") ? cap.url : `https://${host}${cap.url}`;
            if (capUrl) {
              const cr = await fetch(capUrl, { signal: AbortSignal.timeout(8000) });
              if (cr.ok) {
                const vtt = await cr.text();
                const lines = vtt.split("\n");
                const textLines: string[] = [];
                for (const line of lines) {
                  const cleaned = line.replace(/<[^>]+>/g, "").trim();
                  if (cleaned && !cleaned.includes("-->") && cleaned !== "WEBVTT" && !cleaned.startsWith("Kind:") && !cleaned.startsWith("Language:")) {
                    textLines.push(cleaned);
                  }
                }
                const transcript = textLines.join(" ").trim();
                if (transcript.length > 50) {
                  return NextResponse.json({ videoId, title: title || undefined, channel: channel || undefined, transcript, language: getLang(cap) || getLabel(cap) || "unknown", source: "invidious", isAutoGenerated: getLabel(cap).toLowerCase().includes("auto") });
                }
              }
            }
          }
        }
      } catch {}
    }

    try {
      const zai = await ZAI.create();
      const res = await zai.chat.completions.create({
        messages: [
          { role: "system", content: "You are a YouTube video transcript generator. Given a YouTube video title and channel, create a comprehensive, realistic transcript of what the video likely contains. The transcript should be at least 800 words, include greetings, main content sections, and an outro. Use natural conversational language." },
          { role: "user", content: `Generate a full transcript for this YouTube video:\n\nVideo Title: ${title || "Unknown Video"}\nChannel: ${channel || "Unknown"}\nVideo ID: ${videoId}\n\nCreate a detailed, realistic transcript. Include:\n- Opening/greeting\n- Main content discussion\n- Key points and explanations\n- Conclusion/outro\n\nMake it at least 800 words long. Use natural spoken language.` },
        ],
        temperature: 0.5,
      });

      const aiText = res.choices?.[0]?.message?.content?.trim();
      if (aiText && aiText.length > 100) {
        return NextResponse.json({
          videoId, title: title || "Unknown Video", channel: channel || "Unknown",
          transcript: "[AI-Generated Transcript]\n\n" + aiText,
          language: "en", source: "ai-generated", isAutoGenerated: true,
        });
      }
    } catch {}

    return NextResponse.json({
      videoId, title: title || "Unknown Video", channel: channel || "Unknown",
      transcript: "Transcript not available for this video.\n\nVideo: " + (title || videoId) + "\nChannel: " + (channel || "Unknown") + "\n\nThis video may not have captions enabled. Try a video with subtitles.",
      language: "n/a", source: "fallback", isAutoGenerated: false,
    });
  } catch (e: unknown) {
    return NextResponse.json({ error: e instanceof Error ? e.message : "Failed" }, { status: 500 });
  }
  }
